"""
appointment_orders.py
Routes:
  GET    /api/appointment-orders/               list (HR=all, employee/manager=own)
  GET    /api/appointment-orders/<id>           get single
  POST   /api/appointment-orders/               create draft from template + fields
  POST   /api/appointment-orders/<id>/submit    draft → pending_hr_head
  POST   /api/appointment-orders/<id>/hr-action HR Head approve / reject
  GET    /api/appointment-orders/<id>/download  download approved DOCX or PDF
  DELETE /api/appointment-orders/<id>           delete draft/rejected (admin/hr_head)

Lifecycle:  draft → pending_hr_head → approved / rejected
On approval: DOCX generated by replacing {{placeholders}} in template with
             the values the employee filled in.
All files stored in MongoDB GridFS — no local disk dependency.
"""

from flask import Blueprint, request, jsonify, current_app, send_file
from flask_jwt_extended import jwt_required, get_jwt_identity
from datetime import datetime
from bson import ObjectId
from io import BytesIO
import os, uuid, gridfs, tempfile

from services.letter_generator import generate_letter_docx, generate_letter_pdf

appointment_orders_bp = Blueprint('appointment_orders', __name__)

DELETABLE_STATUSES = {'draft', 'rejected'}


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def get_fs():
    return gridfs.GridFS(current_app.db, collection='files_fs')


def get_template_fs():
    return gridfs.GridFS(current_app.db, collection='templates_fs')


def _get_caller(db, uid):
    user = db.users.find_one({'_id': ObjectId(uid)})
    if not user:
        return None, (jsonify({'error': 'User not found'}), 404)
    return user, None


def _enrich(order, db):
    order['_id'] = str(order['_id'])
    try:
        emp = db.employees.find_one({'_id': ObjectId(order.get('employee_id', ''))})
        order['employee_name'] = emp.get('name', 'Unknown') if emp else 'Unknown'
        order['employee_code'] = emp.get('employee_id', '')  if emp else ''
    except Exception:
        order['employee_name'] = 'Unknown'
        order['employee_code'] = ''
    order.pop('docx_path', None)
    order.pop('pdf_path', None)
    return order


def _get_template_bytes(tmpl):
    """
    Get template file bytes from GridFS (new) or disk (legacy).
    Returns bytes or raises ValueError.
    """
    if tmpl.get('gridfs_id'):
        fs = get_template_fs()
        grid_out = fs.get(ObjectId(tmpl['gridfs_id']))
        return grid_out.read()
    elif tmpl.get('file_path') and os.path.exists(tmpl['file_path']):
        with open(tmpl['file_path'], 'rb') as f:
            return f.read()
    else:
        raise ValueError(f"Template '{tmpl.get('name')}' file not found. Please re-upload it.")


def _generate_docs_to_gridfs(tmpl, details, ref):
    """
    Generate DOCX (and PDF if possible) from template, save to GridFS.
    Returns (docx_gridfs_id, pdf_gridfs_id) — pdf may be None.
    """
    fs = get_fs()
    tmpl_bytes = _get_template_bytes(tmpl)

    with tempfile.TemporaryDirectory() as tmp:
        # Write template to temp dir
        tmpl_path = os.path.join(tmp, 'template.docx')
        with open(tmpl_path, 'wb') as f:
            f.write(tmpl_bytes)

        base      = ref.replace('/', '-').replace(' ', '_')
        docx_path = os.path.join(tmp, base + '.docx')
        pdf_path  = os.path.join(tmp, base + '.pdf')

        generate_letter_docx(tmpl_path, details, docx_path)

        # Save DOCX to GridFS
        with open(docx_path, 'rb') as f:
            docx_gid = str(fs.put(f.read(), filename=base + '.docx'))

        # Try PDF
        pdf_gid = None
        pdf_result = generate_letter_pdf(docx_path, pdf_path)
        if pdf_result and os.path.exists(pdf_result):
            with open(pdf_result, 'rb') as f:
                pdf_gid = str(fs.put(f.read(), filename=base + '.pdf'))

    return docx_gid, pdf_gid


# ─────────────────────────────────────────────────────────────────────────────
# Routes
# ─────────────────────────────────────────────────────────────────────────────

@appointment_orders_bp.route('/', methods=['GET'])
@jwt_required()
def list_orders():
    db  = current_app.db
    uid = get_jwt_identity()
    caller, err = _get_caller(db, uid)
    if err: return err

    query = {}
    if caller.get('role') in ('employee', 'manager'):
        emp_ref = caller.get('employee_ref', '')
        query['employee_id'] = emp_ref
    else:
        filter_emp_id = request.args.get('employee_id')
        if filter_emp_id:
            query['employee_id'] = filter_emp_id

    status = request.args.get('status')
    if status:
        query['status'] = status

    orders = list(db.appointment_orders.find(query).sort('created_at', -1))
    return jsonify([_enrich(o, db) for o in orders])


@appointment_orders_bp.route('/preview-template', methods=['POST'])
@jwt_required()
def preview_template():
    db          = current_app.db
    data        = request.json or {}
    template_id = data.get('template_id')
    fields      = data.get('fields', {})

    tmpl = db.templates.find_one({'_id': ObjectId(template_id)})
    if not tmpl:
        return jsonify({'error': 'Template not found'}), 404

    try:
        tmpl_bytes = _get_template_bytes(tmpl)
    except ValueError as e:
        return jsonify({'error': str(e)}), 404

    with tempfile.TemporaryDirectory() as tmp:
        tmpl_path = os.path.join(tmp, 'template.docx')
        with open(tmpl_path, 'wb') as f:
            f.write(tmpl_bytes)

        base      = f"preview_temp_{uuid.uuid4().hex}"
        docx_path = os.path.join(tmp, base + '.docx')
        pdf_path  = os.path.join(tmp, base + '.pdf')

        try:
            generate_letter_docx(tmpl_path, fields, docx_path)
        except Exception as e:
            return jsonify({'error': f'Preview failed: {e}'}), 500

        pdf_result = generate_letter_pdf(docx_path, pdf_path)

        if pdf_result and os.path.exists(pdf_result):
            with open(pdf_result, 'rb') as f:
                pdf_bytes = f.read()
            return send_file(BytesIO(pdf_bytes), mimetype='application/pdf')
        elif os.path.exists(docx_path):
            with open(docx_path, 'rb') as f:
                docx_bytes = f.read()
            return send_file(
                BytesIO(docx_bytes),
                mimetype='application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                as_attachment=True,
                download_name='preview.docx'
            )

    return jsonify({'error': 'Preview generation failed'}), 500


@appointment_orders_bp.route('/<oid>/preview', methods=['GET'])
@jwt_required()
def preview_appointment_order(oid):
    db  = current_app.db
    uid = get_jwt_identity()
    caller, err = _get_caller(db, uid)
    if err: return err

    if caller.get('role') not in ('hr_head', 'admin', 'manager', 'employee', 'hr'):
        return jsonify({'error': 'Access denied'}), 403

    o = db.appointment_orders.find_one({'_id': ObjectId(oid)})
    if not o:
        return jsonify({'error': 'Order not found'}), 404

    tmpl_id = o.get('template_id')
    tmpl = None
    if tmpl_id:
        try:
            tmpl = db.templates.find_one({'_id': ObjectId(tmpl_id)})
        except Exception:
            pass
    if not tmpl:
        tmpl = db.templates.find_one({'type': 'appointment_order', 'is_active': True})
    if not tmpl:
        return jsonify({'error': 'No appointment order template found'}), 404

    try:
        tmpl_bytes = _get_template_bytes(tmpl)
    except ValueError as e:
        return jsonify({'error': str(e)}), 404

    details = dict(o.get('details', {}))
    details['approval_date'] = datetime.now().strftime('%d-%m-%Y')

    with tempfile.TemporaryDirectory() as tmp:
        tmpl_path = os.path.join(tmp, 'template.docx')
        with open(tmpl_path, 'wb') as f:
            f.write(tmpl_bytes)

        base      = f"preview_{oid}"
        docx_path = os.path.join(tmp, base + '.docx')
        pdf_path  = os.path.join(tmp, base + '.pdf')

        try:
            generate_letter_docx(tmpl_path, details, docx_path)
        except Exception as e:
            return jsonify({'error': f'Preview generation failed: {e}'}), 500

        pdf_result = generate_letter_pdf(docx_path, pdf_path)

        if pdf_result and os.path.exists(pdf_result):
            with open(pdf_result, 'rb') as f:
                pdf_bytes = f.read()
            return send_file(BytesIO(pdf_bytes), mimetype='application/pdf')
        elif os.path.exists(docx_path):
            with open(docx_path, 'rb') as f:
                docx_bytes = f.read()
            return send_file(
                BytesIO(docx_bytes),
                mimetype='application/vnd.openxmlformats-officedocument.wordprocessingml.document',
                as_attachment=True,
                download_name='preview.docx'
            )

    return jsonify({'error': 'Preview generation failed — LibreOffice may not be available'}), 500


@appointment_orders_bp.route('/<oid>', methods=['GET'])
@jwt_required()
def get_order(oid):
    db = current_app.db
    o  = db.appointment_orders.find_one({'_id': ObjectId(oid)})
    if not o: return jsonify({'error': 'Not found'}), 404
    return jsonify(_enrich(o, db))


@appointment_orders_bp.route('/', methods=['POST'])
@jwt_required()
def create_order():
    db  = current_app.db
    uid = get_jwt_identity()
    caller, err = _get_caller(db, uid)
    if err: return err

    data = request.json or {}

    if caller.get('role') not in ('hr', 'hr_head', 'admin'):
        return jsonify({'error': 'Only HR can create appointment orders'}), 403

    employee_id = data.get('employee_id', '')
    if not employee_id:
        return jsonify({'error': 'employee_id is required'}), 400

    emp = db.employees.find_one({'_id': ObjectId(employee_id)})
    if not emp:
        return jsonify({'error': 'Employee not found'}), 404

    existing = db.appointment_orders.count_documents({'employee_id': employee_id})
    ref_num  = f"AO-{emp.get('employee_id', 'EMP')}-{str(existing + 1).zfill(3)}"

    template_id = data.get('template_id')
    if not template_id:
        return jsonify({'error': 'template_id is required'}), 400
    tmpl = db.templates.find_one({'_id': ObjectId(template_id)})
    if not tmpl:
        return jsonify({'error': 'Template not found'}), 404

    fields = data.get('fields') or {}
    details = {
        **fields,
        'date':             datetime.now().strftime('%d-%m-%Y'),
        'reference_number': ref_num,
        'employee_id_code': emp.get('employee_id', ''),
    }

    doc = {
        'employee_id':      employee_id,
        'template_id':      template_id,
        'reference_number': ref_num,
        'status':           'draft',
        'details':          details,
        'approval_history': [],
        'created_by':       uid,
        'created_at':       datetime.utcnow(),
    }
    result = db.appointment_orders.insert_one(doc)
    return jsonify({'id': str(result.inserted_id), 'reference_number': ref_num}), 201


@appointment_orders_bp.route('/<oid>/submit', methods=['POST'])
@jwt_required()
def submit_order(oid):
    db  = current_app.db
    uid = get_jwt_identity()
    caller, err = _get_caller(db, uid)
    if err: return err
    if caller.get('role') not in ('hr', 'hr_head', 'admin'):
        return jsonify({'error': 'Only HR can submit appointment orders'}), 403
    o = db.appointment_orders.find_one({'_id': ObjectId(oid)})
    if not o:                  return jsonify({'error': 'Not found'}), 404
    if o['status'] != 'draft': return jsonify({'error': 'Only drafts can be submitted'}), 400

    db.appointment_orders.update_one({'_id': ObjectId(oid)}, {
        '$set':  {'status': 'pending_hr_head', 'updated_at': datetime.utcnow()},
        '$push': {'approval_history': {
            'user_id': uid, 'action': 'submitted',
            'from': 'draft', 'to': 'pending_hr_head',
            'timestamp': datetime.utcnow().isoformat(),
        }},
    })
    return jsonify({'message': 'Submitted to HR Head for approval'})


@appointment_orders_bp.route('/<oid>/update-fields', methods=['POST'])
@jwt_required()
def update_fields(oid):
    db  = current_app.db
    uid = get_jwt_identity()
    caller = db.users.find_one({'_id': ObjectId(uid)})
    if not caller:
        return jsonify({'error': 'User not found'}), 404
    if caller.get('role') not in ('hr', 'hr_head', 'admin'):
        return jsonify({'error': 'Only HR can edit appointment orders'}), 403

    o = db.appointment_orders.find_one({'_id': ObjectId(oid)})
    if not o: return jsonify({'error': 'Not found'}), 404
    if o['status'] != 'rejected':
        return jsonify({'error': 'Only rejected orders can be edited'}), 400

    data   = request.json or {}
    fields = data.get('fields', {})
    if not fields:
        return jsonify({'error': 'No fields provided'}), 400

    merged = {**o.get('details', {}), **fields}

    db.appointment_orders.update_one({'_id': ObjectId(oid)}, {
        '$set': {
            'details':    merged,
            'fields':     fields,
            'status':     'draft',
            'updated_at': datetime.utcnow(),
        },
        '$push': {'approval_history': {
            'user_id':   uid, 'action': 'edited_after_rejection',
            'from': 'rejected', 'to': 'draft',
            'timestamp': datetime.utcnow().isoformat(),
        }},
    })
    return jsonify({'message': 'Fields updated. Order is now a draft — ready to resubmit.'})


@appointment_orders_bp.route('/<oid>/resubmit', methods=['POST'])
@jwt_required()
def resubmit_order(oid):
    db  = current_app.db
    uid = get_jwt_identity()
    caller = db.users.find_one({'_id': ObjectId(uid)})
    if not caller:
        return jsonify({'error': 'User not found'}), 404

    o = db.appointment_orders.find_one({'_id': ObjectId(oid)})
    if not o: return jsonify({'error': 'Not found'}), 404

    if caller.get('role') not in ('hr', 'hr_head', 'admin'):
        return jsonify({'error': 'Only HR can resubmit appointment orders'}), 403

    if o['status'] != 'draft':
        return jsonify({'error': 'Only draft orders can be resubmitted'}), 400

    db.appointment_orders.update_one({'_id': ObjectId(oid)}, {
        '$set':  {'status': 'pending_hr_head', 'updated_at': datetime.utcnow()},
        '$push': {'approval_history': {
            'user_id':   uid, 'action': 'resubmitted',
            'from': 'draft', 'to': 'pending_hr_head',
            'timestamp': datetime.utcnow().isoformat(),
        }},
    })
    return jsonify({'message': 'Resubmitted to HR Head for approval.'})


@appointment_orders_bp.route('/<oid>/hr-action', methods=['POST'])
@jwt_required()
def hr_action(oid):
    db  = current_app.db
    uid = get_jwt_identity()
    caller, err = _get_caller(db, uid)
    if err: return err
    if caller.get('role') not in ('hr_head', 'admin'):
        return jsonify({'error': 'Only HR Head or Admin can approve appointment orders'}), 403

    o = db.appointment_orders.find_one({'_id': ObjectId(oid)})
    if not o: return jsonify({'error': 'Not found'}), 404
    if o['status'] != 'pending_hr_head':
        return jsonify({'error': f"Status is '{o['status']}', expected pending_hr_head"}), 400

    data    = request.json or {}
    act     = data.get('action')
    remarks = data.get('remarks', '').strip()

    if act not in ('approve', 'reject'):
        return jsonify({'error': "action must be 'approve' or 'reject'"}), 400
    if act == 'reject' and not remarks:
        return jsonify({'error': 'Rejection reason is required'}), 400

    new_status = 'approved' if act == 'approve' else 'rejected'

    update_ops = {
        '$set':  {'status': new_status, 'updated_at': datetime.utcnow()},
        '$push': {'approval_history': {
            'user_id':   uid,
            'user_name': caller.get('name', ''),
            'role':      caller.get('role'),
            'action':    act,
            'from':      'pending_hr_head',
            'to':        new_status,
            'remarks':   remarks,
            'timestamp': datetime.utcnow().isoformat(),
        }},
    }

    # ── On approval: generate DOCX/PDF and save to GridFS ──────────────────
    if act == 'approve':
        tmpl_id = o.get('template_id') or data.get('template_id')
        if tmpl_id:
            tmpl = db.templates.find_one({'_id': ObjectId(tmpl_id)})
        else:
            tmpl = db.templates.find_one({'type': 'appointment_order', 'is_active': True})

        if tmpl:
            details = dict(o.get('details', {}))
            details['approval_date'] = datetime.now().strftime('%d-%m-%Y')
            ref = o.get('reference_number', str(oid))

            try:
                docx_gid, pdf_gid = _generate_docs_to_gridfs(tmpl, details, ref)
                update_ops['$set']['docx_gridfs_id'] = docx_gid
                update_ops['$set']['pdf_gridfs_id']  = pdf_gid
                update_ops['$set']['template_id']    = str(tmpl['_id'])
            except Exception as e:
                import logging
                logging.getLogger(__name__).warning(f'AO doc generation failed: {e}')
        else:
            import logging
            logging.getLogger(__name__).warning('AO approval: no template found')

    update_ops['$set']['employee_notified'] = False
    db.appointment_orders.update_one({'_id': ObjectId(oid)}, update_ops)
    return jsonify({'message': f'Appointment order {act}d', 'new_status': new_status})


@appointment_orders_bp.route('/<oid>/download', methods=['GET'])
@jwt_required()
def download(oid):
    db  = current_app.db
    uid = get_jwt_identity()
    caller, err = _get_caller(db, uid)
    if err: return err

    fmt = request.args.get('format', 'pdf')
    o   = db.appointment_orders.find_one({'_id': ObjectId(oid)})
    if not o: return jsonify({'error': 'Not found'}), 404
    if o.get('status') != 'approved':
        return jsonify({'error': 'Appointment order must be approved before downloading'}), 400

    if caller.get('role') in ('employee', 'manager'):
        if o.get('employee_id') != caller.get('employee_ref', ''):
            return jsonify({'error': 'Access denied'}), 403

    ref = o.get('reference_number', 'AO')
    fs  = get_fs()

    # Try GridFS first
    if fmt == 'pdf' and o.get('pdf_gridfs_id'):
        try:
            grid_out = fs.get(ObjectId(o['pdf_gridfs_id']))
            return send_file(BytesIO(grid_out.read()), as_attachment=True,
                             download_name=f"{ref}.pdf", mimetype='application/pdf')
        except Exception:
            pass

    if o.get('docx_gridfs_id'):
        try:
            grid_out = fs.get(ObjectId(o['docx_gridfs_id']))
            return send_file(BytesIO(grid_out.read()), as_attachment=True,
                             download_name=f"{ref}.docx",
                             mimetype='application/vnd.openxmlformats-officedocument.wordprocessingml.document')
        except Exception:
            pass

    # Legacy fallback: disk paths
    if fmt == 'pdf' and o.get('pdf_path') and os.path.exists(o['pdf_path']):
        return send_file(o['pdf_path'], as_attachment=True, download_name=f"{ref}.pdf")
    if o.get('docx_path') and os.path.exists(o['docx_path']):
        return send_file(o['docx_path'], as_attachment=True, download_name=f"{ref}.docx")

    return jsonify({'error': 'Generated file not found. Try re-approving.'}), 404


@appointment_orders_bp.route('/<oid>/mark-read', methods=['POST'])
@jwt_required()
def mark_read(oid):
    db = current_app.db
    db.appointment_orders.update_one(
        {'_id': ObjectId(oid)},
        {'$set': {'employee_notified': True}}
    )
    return jsonify({'message': 'Marked as read'})


@appointment_orders_bp.route('/<oid>', methods=['DELETE'])
@jwt_required()
def delete_order(oid):
    db  = current_app.db
    uid = get_jwt_identity()
    caller, err = _get_caller(db, uid)
    if err: return err
    if caller.get('role') not in ('admin', 'hr_head'):
        return jsonify({'error': 'Only Admin or HR Head can delete appointment orders'}), 403
    o = db.appointment_orders.find_one({'_id': ObjectId(oid)})
    if not o: return jsonify({'error': 'Not found'}), 404
    if o['status'] not in DELETABLE_STATUSES:
        return jsonify({'error': f"Cannot delete a '{o['status']}' order"}), 400

    # Delete from GridFS
    fs = get_fs()
    for gid_key in ('docx_gridfs_id', 'pdf_gridfs_id'):
        gid = o.get(gid_key)
        if gid:
            try:
                fs.delete(ObjectId(gid))
            except Exception:
                pass

    # Legacy disk cleanup
    for pk in ('docx_path', 'pdf_path'):
        fp = o.get(pk)
        if fp and os.path.exists(fp):
            try:
                os.remove(fp)
            except OSError:
                pass

    db.appointment_orders.delete_one({'_id': ObjectId(oid)})
    return jsonify({'message': 'Deleted'})