"""
appointment_orders.py
Routes:
  GET    /api/appointment-orders/               list (HR=all, employee/manager=own)
  GET    /api/appointment-orders/<id>           get single
  POST   /api/appointment-orders/               create draft from template + fields
  POST   /api/appointment-orders/<id>/submit    draft → pending_hr_head
  POST   /api/appointment-orders/<id>/hr-action HR Head approve / reject
  GET    /api/appointment-orders/<id>/download  download approved DOCX or PDF
  DELETE /api/appointment-orders/<id>           delete draft/rejected (admin/hr_head)

Lifecycle:  draft → pending_hr_head → approved / rejected
On approval: DOCX generated by replacing {{placeholders}} in template with
             the values the employee filled in.
"""

from flask import Blueprint, request, jsonify, current_app, send_file
from flask_jwt_extended import jwt_required, get_jwt_identity
from datetime import datetime
from bson import ObjectId
import os

from services.letter_generator import generate_letter_docx, generate_letter_pdf

appointment_orders_bp = Blueprint('appointment_orders', __name__)

DELETABLE_STATUSES = {'draft', 'rejected'}


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────

def _get_caller(db, uid):
    user = db.users.find_one({'_id': ObjectId(uid)})
    if not user:
        return None, (jsonify({'error': 'User not found'}), 404)
    return user, None


def _enrich(order, db):
    order['_id'] = str(order['_id'])
    try:
        emp = db.employees.find_one({'_id': ObjectId(order.get('employee_id', ''))})
        order['employee_name'] = emp.get('name', 'Unknown') if emp else 'Unknown'
        order['employee_code'] = emp.get('employee_id', '')  if emp else ''
    except Exception:
        order['employee_name'] = 'Unknown'
        order['employee_code'] = ''
    order.pop('docx_path', None)
    order.pop('pdf_path', None)
    return order


# ─────────────────────────────────────────────────────────────────────────────
# Routes
# ─────────────────────────────────────────────────────────────────────────────

@appointment_orders_bp.route('/', methods=['GET'])
@jwt_required()
def list_orders():
    db  = current_app.db
    uid = get_jwt_identity()
    caller, err = _get_caller(db, uid)
    if err: return err

    query = {}
    # Employees and managers see only their own
    if caller.get('role') in ('employee', 'manager'):
        emp_ref = caller.get('employee_ref', '')
        query['employee_id'] = emp_ref

    status = request.args.get('status')
    if status:
        query['status'] = status

    orders = list(db.appointment_orders.find(query).sort('created_at', -1))
    return jsonify([_enrich(o, db) for o in orders])


@appointment_orders_bp.route('/<oid>', methods=['GET'])
@jwt_required()
def get_order(oid):
    db = current_app.db
    o  = db.appointment_orders.find_one({'_id': ObjectId(oid)})
    if not o: return jsonify({'error': 'Not found'}), 404
    return jsonify(_enrich(o, db))


@appointment_orders_bp.route('/', methods=['POST'])
@jwt_required()
def create_order():
    """
    Create a draft appointment order.
    Body: { template_id, fields: { placeholder_key: value, ... } }

    The `fields` dict contains every placeholder the employee filled in.
    Auto-fields (date, reference_number) are set server-side.
    """
    db  = current_app.db
    uid = get_jwt_identity()
    caller, err = _get_caller(db, uid)
    if err: return err

    data = request.json or {}

    # Resolve employee
    if caller.get('role') in ('employee', 'manager'):
        employee_id = caller.get('employee_ref', '')
    else:
        employee_id = data.get('employee_id', '')

    if not employee_id:
        return jsonify({'error': 'employee_id is required'}), 400

    emp = db.employees.find_one({'_id': ObjectId(employee_id)})
    if not emp:
        return jsonify({'error': 'Employee not found'}), 404

    # Auto-generate reference number: AO-EMP001-001
    existing = db.appointment_orders.count_documents({'employee_id': employee_id})
    ref_num  = f"AO-{emp.get('employee_id', 'EMP')}-{str(existing + 1).zfill(3)}"

    # Validate template exists
    template_id = data.get('template_id')
    if not template_id:
        return jsonify({'error': 'template_id is required'}), 400
    tmpl = db.templates.find_one({'_id': ObjectId(template_id)})
    if not tmpl:
        return jsonify({'error': 'Template not found'}), 404

    # Merge employee-filled fields with auto-set fields
    fields = data.get('fields') or {}
    details = {
        **fields,                                               # all employee-filled placeholders
        'date':             datetime.now().strftime('%d-%m-%Y'),  # auto
        'reference_number': ref_num,                           # auto
        'employee_id_code': emp.get('employee_id', ''),        # auto
    }

    doc = {
        'employee_id':      employee_id,
        'template_id':      template_id,
        'reference_number': ref_num,
        'status':           'draft',
        'details':          details,
        'approval_history': [],
        'created_by':       uid,
        'created_at':       datetime.utcnow(),
    }
    result = db.appointment_orders.insert_one(doc)
    return jsonify({'id': str(result.inserted_id), 'reference_number': ref_num}), 201


@appointment_orders_bp.route('/<oid>/submit', methods=['POST'])
@jwt_required()
def submit_order(oid):
    """Submit draft → pending_hr_head."""
    db  = current_app.db
    uid = get_jwt_identity()
    o   = db.appointment_orders.find_one({'_id': ObjectId(oid)})
    if not o:                  return jsonify({'error': 'Not found'}), 404
    if o['status'] != 'draft': return jsonify({'error': 'Only drafts can be submitted'}), 400

    db.appointment_orders.update_one({'_id': ObjectId(oid)}, {
        '$set':  {'status': 'pending_hr_head', 'updated_at': datetime.utcnow()},
        '$push': {'approval_history': {
            'user_id': uid, 'action': 'submitted',
            'from': 'draft', 'to': 'pending_hr_head',
            'timestamp': datetime.utcnow().isoformat(),
        }},
    })
    return jsonify({'message': 'Submitted to HR Head for approval'})


@appointment_orders_bp.route('/<oid>/hr-action', methods=['POST'])
@jwt_required()
def hr_action(oid):
    """
    HR Head approves or rejects.
    On approval: generate DOCX/PDF by filling template placeholders with
                 the details stored in the order.
    POST { action: 'approve'|'reject', remarks: '' }
    """
    db  = current_app.db
    uid = get_jwt_identity()
    caller, err = _get_caller(db, uid)
    if err: return err
    if caller.get('role') not in ('hr_head', 'admin'):
        return jsonify({'error': 'Only HR Head or Admin can approve appointment orders'}), 403

    o = db.appointment_orders.find_one({'_id': ObjectId(oid)})
    if not o:                          return jsonify({'error': 'Not found'}), 404
    if o['status'] != 'pending_hr_head':
        return jsonify({'error': f"Status is '{o['status']}', expected pending_hr_head"}), 400

    data    = request.json or {}
    act     = data.get('action')
    remarks = data.get('remarks', '').strip()

    if act not in ('approve', 'reject'):
        return jsonify({'error': "action must be 'approve' or 'reject'"}), 400
    if act == 'reject' and not remarks:
        return jsonify({'error': 'Rejection reason is required'}), 400

    new_status = 'approved' if act == 'approve' else 'rejected'

    update_ops = {
        '$set':  {'status': new_status, 'updated_at': datetime.utcnow()},
        '$push': {'approval_history': {
            'user_id':   uid,
            'user_name': caller.get('name', ''),
            'role':      caller.get('role'),
            'action':    act,
            'from':      'pending_hr_head',
            'to':        new_status,
            'remarks':   remarks,
            'timestamp': datetime.utcnow().isoformat(),
        }},
    }

    # ── On approval: generate DOCX from template ──────────────────────────
    if act == 'approve':
        # Use template_id stored on the order, fall back to any active AO template
        tmpl_id = o.get('template_id') or data.get('template_id')
        if tmpl_id:
            tmpl = db.templates.find_one({'_id': ObjectId(tmpl_id)})
        else:
            tmpl = db.templates.find_one({'type': 'appointment_order', 'is_active': True})

        if tmpl and tmpl.get('file_path') and os.path.exists(tmpl['file_path']):
            details = dict(o.get('details', {}))
            details['approval_date'] = datetime.now().strftime('%d-%m-%Y')

            year    = datetime.now().strftime('%Y')
            out_dir = os.path.join(current_app.config['STORAGE_ROOT'], 'appointment_orders', year)
            os.makedirs(out_dir, exist_ok=True)

            ref      = o.get('reference_number', str(oid))
            base     = ref.replace('/', '-').replace(' ', '_')
            docx_path = os.path.join(out_dir, base + '.docx')
            pdf_path  = os.path.join(out_dir, base + '.pdf')

            try:
                generate_letter_docx(tmpl['file_path'], details, docx_path)
                pdf_result = generate_letter_pdf(docx_path, pdf_path)
                update_ops['$set']['docx_path'] = docx_path
                update_ops['$set']['pdf_path']  = pdf_result
                update_ops['$set']['template_id'] = str(tmpl['_id'])
            except Exception as e:
                import logging
                logging.getLogger(__name__).warning(f'AO doc generation failed: {e}')
        else:
            import logging
            logging.getLogger(__name__).warning(f'AO approval: template not found or missing file')

    db.appointment_orders.update_one({'_id': ObjectId(oid)}, update_ops)
    return jsonify({'message': f'Appointment order {act}d', 'new_status': new_status})


@appointment_orders_bp.route('/<oid>/download', methods=['GET'])
@jwt_required()
def download(oid):
    db  = current_app.db
    uid = get_jwt_identity()
    caller, err = _get_caller(db, uid)
    if err: return err

    fmt = request.args.get('format', 'pdf')
    o   = db.appointment_orders.find_one({'_id': ObjectId(oid)})
    if not o: return jsonify({'error': 'Not found'}), 404
    if o.get('status') != 'approved':
        return jsonify({'error': 'Appointment order must be approved before downloading'}), 400

    # Access control: employee/manager can only download their own
    if caller.get('role') in ('employee', 'manager'):
        if o.get('employee_id') != caller.get('employee_ref', ''):
            return jsonify({'error': 'Access denied'}), 403

    ref = o.get('reference_number', 'AO')

    if fmt == 'pdf' and o.get('pdf_path') and os.path.exists(o['pdf_path']):
        return send_file(o['pdf_path'], as_attachment=True, download_name=f"{ref}.pdf")
    if o.get('docx_path') and os.path.exists(o['docx_path']):
        return send_file(o['docx_path'], as_attachment=True, download_name=f"{ref}.docx")

    return jsonify({'error': 'Generated file not found on server. Try re-approving.'}), 404


@appointment_orders_bp.route('/<oid>', methods=['DELETE'])
@jwt_required()
def delete_order(oid):
    db  = current_app.db
    uid = get_jwt_identity()
    caller, err = _get_caller(db, uid)
    if err: return err
    if caller.get('role') not in ('admin', 'hr_head'):
        return jsonify({'error': 'Only Admin or HR Head can delete appointment orders'}), 403
    o = db.appointment_orders.find_one({'_id': ObjectId(oid)})
    if not o: return jsonify({'error': 'Not found'}), 404
    if o['status'] not in DELETABLE_STATUSES:
        return jsonify({'error': f"Cannot delete a '{o['status']}' order"}), 400
    for pk in ('docx_path', 'pdf_path'):
        fp = o.get(pk)
        if fp and os.path.exists(fp):
            try: os.remove(fp)
            except OSError: pass
    db.appointment_orders.delete_one({'_id': ObjectId(oid)})
    return jsonify({'message': 'Deleted'})